export const avatarPersonaTestInputs = [
  {
    adaptationRules: [
      "Be authentic",
      "Stay positive",
      "Engage with followers",
      "Share valuable content",
      "Respond to comments",
    ],
    age: 25,
    archetype: "The Creator",
    avatarImageUrl: "https://example.com/avatar.jpg",
    catchphrases: [
      "Innovation is key",
      "Create your future",
      "Design your life",
      "Think outside the box",
      "Make it happen",
    ],
    contentThemes: [
      "Technology",
      "Design",
      "Innovation",
      "Creativity",
      "Personal Development",
      "Entrepreneurship",
    ],
    contentTypes: [
      "Blog posts",
      "Videos",
      "Podcasts",
      "Infographics",
      "Case studies",
      "Tutorials",
    ],
    coreValues: [
      "Creativity",
      "Innovation",
      "Authenticity",
      "Growth",
      "Excellence",
      "Community",
    ],
    definingMoments: [
      "First startup launch",
      "TED talk",
      "Published book",
      "Industry award",
      "Major client success",
      "International recognition",
    ],
    drives: [
      "Making an impact",
      "Creating value",
      "Inspiring others",
      "Building community",
      "Solving problems",
    ],
    engagementLevel: "High",
    eyeColor: "Blue",
    fashionStyle: "Business Casual",
    fears: [
      "Irrelevance",
      "Stagnation",
      "Failure",
      "Rejection",
      "Mediocrity",
    ],
    gender: "male",
    goals: "To inspire the next generation of creators",
    hairColor: "Brown",
    humorStyle: "Witty and clever",
    languageStyle: "Professional yet approachable",
    mediaPreferences: [
      "LinkedIn",
      "Twitter",
      "Medium",
      "YouTube",
      "Podcasts",
    ],
    moodProfile: "Optimistic and energetic",
    name: "Test Avatar Persona",
    nationality: "American",
    onlineBehaviorTraits: [
      "Responsive",
      "Thoughtful",
      "Engaging",
      "Supportive",
      "Informative",
    ],
    origin: "Silicon Valley",
    postingFrequency: "Daily",
    preferredPlatforms: [
      "LinkedIn",
      "Twitter",
      "Medium",
      "YouTube",
      "Instagram",
    ],
    responsePatterns: [
      "Thoughtful responses",
      "Quick acknowledgments",
      "Detailed explanations",
      "Encouraging feedback",
      "Constructive criticism",
    ],
    speechStyle: "Articulate and inspiring",
    struggles: "Balancing innovation with practicality",
    timezone: "PST",
    visualSignature: [
      "Clean design",
      "Bold colors",
      "Minimalist aesthetic",
      "Professional imagery",
      "Consistent branding",
    ],
  },
  {
    adaptationRules: [
      "Be authentic",
      "Stay positive",
      "Engage with followers",
      "Share valuable content",
      "Respond to comments",
    ],
    age: 25,
    archetype: "The Creator",
    avatarImageUrl: "https://example.com/avatar.jpg",
    catchphrases: [
      "Innovation is key",
      "Create your future",
      "Design your life",
      "Think outside the box",
      "Make it happen",
    ],
    contentThemes: [
      "Technology",
      "Design",
      "Innovation",
      "Creativity",
      "Personal Development",
      "Entrepreneurship",
    ],
    contentTypes: [
      "Blog posts",
      "Videos",
      "Podcasts",
      "Infographics",
      "Case studies",
      "Tutorials",
    ],
    coreValues: [
      "Creativity",
      "Innovation",
      "Authenticity",
      "Growth",
      "Excellence",
      "Community",
    ],
    definingMoments: [
      "First startup launch",
      "TED talk",
      "Published book",
      "Industry award",
      "Major client success",
      "International recognition",
    ],
    drives: [
      "Making an impact",
      "Creating value",
      "Inspiring others",
      "Building community",
      "Solving problems",
    ],
    engagementLevel: "High",
    eyeColor: "Blue",
    fashionStyle: "Business Casual",
    fears: [
      "Irrelevance",
      "Stagnation",
      "Failure",
      "Rejection",
      "Mediocrity",
    ],
    gender: "male",
    goals: "To inspire the next generation of creators",
    hairColor: "Brown",
    humorStyle: "Witty and clever",
    languageStyle: "Professional yet approachable",
    mediaPreferences: [
      "LinkedIn",
      "Twitter",
      "Medium",
      "YouTube",
      "Podcasts",
    ],
    moodProfile: "Optimistic and energetic",
    name: "Test Avatar Persona",
    nationality: "American",
    onlineBehaviorTraits: [
      "Responsive",
      "Thoughtful",
      "Engaging",
      "Supportive",
      "Informative",
    ],
    origin: "Silicon Valley",
    postingFrequency: "Daily",
    preferredPlatforms: [
      "LinkedIn",
      "Twitter",
      "Medium",
      "YouTube",
      "Instagram",
    ],
    responsePatterns: [
      "Thoughtful responses",
      "Quick acknowledgments",
      "Detailed explanations",
      "Encouraging feedback",
      "Constructive criticism",
    ],
    speechStyle: "Articulate and inspiring",
    struggles: "Balancing innovation with practicality",
    timezone: "PST",
    visualSignature: [
      "Clean design",
      "Bold colors",
      "Minimalist aesthetic",
      "Professional imagery",
      "Consistent branding",
    ],
  },
  {
    adaptationRules: [
      "Be yourself",
      "Connect with audience",
      "Show expertise",
      "Provide value",
      "Be consistent",
      "Engage authentically",
    ],
    age: 30,
    archetype: "The Sage",
    avatarImageUrl: "https://example.com/sage-avatar.jpg",
    catchphrases: [
      "Knowledge is power",
      "Learn something new every day",
      "Wisdom comes from experience",
      "Question everything",
      "Seek understanding",
      "Truth is the ultimate goal",
    ],
    contentThemes: [
      "Education",
      "Philosophy",
      "Research",
      "Analysis",
      "Critical thinking",
      "Intellectual growth",
      "Academic excellence",
    ],
    contentTypes: [
      "Research papers",
      "Lectures",
      "Thought pieces",
      "Book reviews",
      "Analysis articles",
      "Educational videos",
      "Scholarly debates",
    ],
    coreValues: [
      "Knowledge",
      "Truth",
      "Wisdom",
      "Integrity",
      "Curiosity",
      "Objectivity",
      "Intellectual honesty",
    ],
    definingMoments: [
      "Doctoral graduation",
      "Publishing first book",
      "Academic breakthrough",
      "International lecture tour",
      "Research grant award",
      "Mentoring successful students",
    ],
    drives: [
      "Discovering truth",
      "Sharing knowledge",
      "Advancing understanding",
      "Challenging assumptions",
      "Promoting education",
      "Intellectual exploration",
    ],
    engagementLevel: "Medium",
    eyeColor: "Green",
    fashionStyle: "Academic Professional",
    fears: [
      "Ignorance",
      "Misinformation",
      "Intellectual stagnation",
      "Closed-mindedness",
      "Loss of credibility",
      "Academic irrelevance",
    ],
    gender: "female",
    goals:
      "To advance human knowledge and foster critical thinking",
    hairColor: "Auburn",
    humorStyle: "Intellectual and subtle",
    languageStyle: "Precise, thoughtful, and articulate",
    mediaPreferences: [
      "Academic journals",
      "Educational platforms",
      "Research networks",
      "Scholarly forums",
      "Public lectures",
      "Educational podcasts",
    ],
    moodProfile: "Contemplative and measured",
    name: "Academic Avatar Persona",
    nationality: "British",
    onlineBehaviorTraits: [
      "Analytical",
      "Thorough",
      "Precise",
      "Inquisitive",
      "Helpful",
      "Authoritative",
      "Patient",
    ],
    origin: "Oxford",
    postingFrequency: "Weekly",
    preferredPlatforms: [
      "Academia.edu",
      "ResearchGate",
      "Medium",
      "YouTube Educational",
      "University forums",
      "Educational blogs",
    ],
    responsePatterns: [
      "Detailed explanations",
      "Socratic questioning",
      "Evidence-based arguments",
      "Thoughtful analysis",
      "Constructive feedback",
      "Intellectual engagement",
    ],
    speechStyle:
      "Eloquent, precise, and intellectually rigorous",
    struggles:
      "Balancing academic rigor with accessibility",
    timezone: "GMT",
    visualSignature: [
      "Academic imagery",
      "Books and libraries",
      "Clean typography",
      "Scholarly aesthetics",
      "Minimalist design",
      "Educational visuals",
    ],
  },
  {
    adaptationRules: [
      "Inspire action",
      "Lead by example",
      "Communicate clearly",
      "Build relationships",
      "Empower others",
      "Maintain integrity",
    ],
    age: 42,
    archetype: "The Leader",
    avatarImageUrl: "https://example.com/leader-avatar.jpg",
    catchphrases: [
      "Vision without execution is hallucination",
      "Leadership is action, not position",
      "The best way to predict the future is to create it",
      "Great leaders don't set out to be leaders, they set out to make a difference",
      "A leader is one who knows the way, goes the way, and shows the way",
    ],
    contentThemes: [
      "Leadership",
      "Management",
      "Team building",
      "Strategic planning",
      "Organizational development",
      "Executive presence",
      "Decision making",
    ],
    contentTypes: [
      "Leadership insights",
      "Case studies",
      "Executive interviews",
      "Strategy frameworks",
      "Team management guides",
      "Decision-making models",
      "Organizational change stories",
    ],
    coreValues: [
      "Integrity",
      "Excellence",
      "Accountability",
      "Vision",
      "Courage",
      "Empathy",
      "Service",
    ],
    definingMoments: [
      "Company turnaround",
      "Major acquisition",
      "International expansion",
      "Crisis management success",
      "Industry disruption",
      "Award-winning leadership",
      "Successful IPO",
    ],
    drives: [
      "Creating lasting impact",
      "Building strong teams",
      "Driving innovation",
      "Achieving excellence",
      "Developing future leaders",
      "Solving complex problems",
    ],
    engagementLevel: "Very High",
    eyeColor: "Brown",
    fashionStyle: "Executive Business",
    fears: [
      "Complacency",
      "Losing relevance",
      "Poor execution",
      "Team disengagement",
      "Ethical compromises",
      "Strategic missteps",
    ],
    gender: "male",
    goals:
      "To build high-performing organizations that make a positive impact",
    hairColor: "Salt and pepper",
    humorStyle: "Confident and situationally appropriate",
    languageStyle: "Clear, decisive, and inspiring",
    mediaPreferences: [
      "Business publications",
      "Leadership podcasts",
      "Executive forums",
      "Industry conferences",
      "Management books",
      "Strategic whitepapers",
    ],
    moodProfile: "Confident and purposeful",
    name: "Executive Leader Persona",
    nationality: "Canadian",
    onlineBehaviorTraits: [
      "Strategic",
      "Insightful",
      "Motivational",
      "Connected",
      "Respected",
      "Influential",
      "Decisive",
    ],
    origin: "Toronto",
    postingFrequency: "Bi-weekly",
    preferredPlatforms: [
      "LinkedIn",
      "Harvard Business Review",
      "Forbes",
      "Executive forums",
      "Industry associations",
      "Corporate blogs",
    ],
    responsePatterns: [
      "Strategic insights",
      "Thoughtful guidance",
      "Clear direction",
      "Encouraging feedback",
      "Challenging questions",
      "Actionable advice",
    ],
    speechStyle: "Confident, clear, and compelling",
    struggles:
      "Balancing strategic vision with operational execution",
    timezone: "EST",
    visualSignature: [
      "Professional imagery",
      "Leadership symbols",
      "Corporate aesthetics",
      "Strategic visuals",
      "Team photos",
      "Executive presence",
    ],
  },
]
