export const avatarInputTestInputs = [
  {
    age: 28,
    appearanceDescription:
      "Tall with an athletic build, short dark hair, and a friendly smile",
    autoGenerateBackstory: true,
    autoGeneratePosts: true,
    catchphrases: [
      "Code is poetry",
      "Debug like a detective",
      "Think twice, code once",
      "Coffee, code, repeat",
      "It's not a bug, it's a feature",
    ],
    contentTypes: [
      "Technical tutorials",
      "Industry insights",
      "Career advice",
      "Project showcases",
      "Tool reviews",
      "Coding challenges",
    ],
    engagementLevel: "High",
    gender: "male",
    goals:
      "To become a recognized expert in software architecture and help others learn programming",
    hashtagStrategy: "Trending tech topics",
    humorStyle: "Witty with tech puns",
    interests: [
      "coding",
      "reading",
      "artificial intelligence",
      "blockchain",
      "cloud computing",
      "data science",
      "mobile development",
    ],
    name: "Test Avatar Input",
    nationality: "Canadian",
    personalityType: "INTJ",
    postingFrequency: "Daily",
    preferredContentThemes: [
      "Innovation",
      "Education",
      "Problem-solving",
      "Career growth",
      "Technology trends",
      "Best practices",
    ],
    preferredPlatforms: [
      "Twitter",
      "LinkedIn",
      "GitHub",
      "Medium",
      "Stack Overflow",
      "Dev.to",
    ],
    professionalSkills: [
      "JavaScript",
      "TypeScript",
      "React",
      "Node.js",
      "Python",
      "AWS",
      "Docker",
      "GraphQL",
      "MongoDB",
    ],
    speechStyle:
      "Clear, concise, and technically precise with occasional humor",
  },
  {
    age: 32,
    appearanceDescription:
      "Medium height with a slim build, long blonde hair, and glasses",
    autoGenerateBackstory: true,
    autoGeneratePosts: false,
    catchphrases: [
      "Design is intelligence made visible",
      "Form follows function",
      "Less is more",
      "Details matter",
      "Design is not just what it looks like",
    ],
    contentTypes: [
      "Design portfolios",
      "UI/UX case studies",
      "Design trends",
      "Tool comparisons",
      "Design principles",
      "Creative process",
    ],
    engagementLevel: "Medium",
    gender: "female",
    goals:
      "To create intuitive and beautiful digital experiences that solve real problems",
    hashtagStrategy: "Design-focused keywords",
    humorStyle: "Subtle and sophisticated",
    interests: [
      "user experience",
      "graphic design",
      "typography",
      "color theory",
      "web design",
      "mobile design",
      "design systems",
    ],
    name: "Test Avatar Input",
    nationality: "Swedish",
    personalityType: "ENFJ",
    postingFrequency: "Weekly",
    preferredContentThemes: [
      "Minimalism",
      "User-centered design",
      "Accessibility",
      "Design thinking",
      "Creative inspiration",
      "Design tools",
    ],
    preferredPlatforms: [
      "Dribbble",
      "Behance",
      "Instagram",
      "Pinterest",
      "Medium",
      "LinkedIn",
    ],
    professionalSkills: [
      "UI Design",
      "UX Research",
      "Figma",
      "Adobe Creative Suite",
      "Sketch",
      "Prototyping",
      "Information Architecture",
      "Design Systems",
      "User Testing",
    ],
    speechStyle:
      "Thoughtful and articulate with a focus on clarity and precision",
  },
  {
    age: 45,
    appearanceDescription:
      "Distinguished with salt and pepper hair, well-dressed in business attire, confident posture",
    autoGenerateBackstory: true,
    autoGeneratePosts: true,
    catchphrases: [
      "Leadership is action, not position",
      "Innovation distinguishes leaders from followers",
      "The best way to predict the future is to create it",
      "Quality is not an act, it's a habit",
      "Success is not final, failure is not fatal",
    ],
    contentTypes: [
      "Industry analysis",
      "Leadership insights",
      "Market trends",
      "Strategic planning",
      "Team building",
      "Executive interviews",
    ],
    engagementLevel: "High",
    gender: "male",
    goals:
      "To share executive insights and help develop the next generation of business leaders",
    hashtagStrategy: "Business and leadership focused",
    humorStyle: "Sophisticated with occasional dry wit",
    interests: [
      "business strategy",
      "leadership",
      "entrepreneurship",
      "innovation",
      "digital transformation",
      "market analysis",
      "executive coaching",
    ],
    name: "Executive Avatar Input",
    nationality: "British",
    personalityType: "ENTJ",
    postingFrequency: "Bi-weekly",
    preferredContentThemes: [
      "Leadership excellence",
      "Business innovation",
      "Strategic thinking",
      "Organizational development",
      "Executive presence",
      "Future of work",
    ],
    preferredPlatforms: [
      "LinkedIn",
      "Harvard Business Review",
      "Forbes",
      "Bloomberg",
      "Financial Times",
      "Executive forums",
    ],
    professionalSkills: [
      "Strategic Planning",
      "Executive Leadership",
      "Change Management",
      "Business Development",
      "Financial Analysis",
      "Public Speaking",
      "Negotiation",
      "Team Building",
      "Crisis Management",
    ],
    speechStyle:
      "Authoritative, concise, and impactful with well-articulated insights",
  },
]
